### ISSUE TITLE
Signing in via Native Google login, and then via native Apple login throws an exception

### ISSUE THREAD

**Issue by dshukertjr** [supabase/gotrue#1233]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After setting up native Google and Apple login for my remote Supabase instance, I sign in a user via native Google login. After that, I sign out and then sign in via native Apple login with the same email address. This signing in with native Apple login throws `Unacceptable audience in id_token` error on Gotrue. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup native Google and Apple login.
2. Sign in via native Google login
3. Sign out
4. Sign in via native Apple login with the same email address and observe the exception thrown from Gotrue

## Expected behavior

Performing Google login and Apple login on the same email address works fine. 

## System information

- OS: iOS
- Version of supabase-flutter: 1.10.14

## Additional context

Related https://github.com/supabase/supabase-flutter/issues/5#issuecomment-1687945257

**Comment by Dr-Usman** [comment]
Is there any solution? I am facing it with `singInWithApple()` on ios and also i have implemented native login and get idtoken and then pass it to the `signInWithIdToken()` but still same error. 

> AuthException(message: Unacceptable audience in id_token, statusCode:400)

**Comment by Dr-Usman** [comment]
Thank you for replying @dshukertjr . I implemented 2 months ago and i have checked and tested last month it was working fine.  It stopped working suddenly in last week.
Thank you for the answer. It solves the issue and working fine now. ✅😀

**Comment by hf** [comment]
Hey everyone. We did some digging on this, it appears that we had introduced a bug temporarily with the handling of these configs. If you had setup Apple or Google sign in then, the configs were likely saved incorrectly. This appears to have been a very low number of projects affected, but we've now fixed all of the project's settings. 

Sorry about that!

I'll close this issue for now.

**Comment by iseruuuuu** [comment]
Hello, I have been implementing `sign in with apple` since 2024/02/18.
I have implemented sign in with apple since 2024/02/18, but I got the error `Unacceptable audience in id_token`.

I tried to turn off "sign in with Apple" and turn it on again as mentioned in the comments, but the error remained the same.

In my case, the address of the device to log in is an address that I have never registered, so I think the situation is different from what is outlined in the issue, but I am facing the same error.

As for the login implementation, it is exactly the same as the new Apple login implementation at

https://supabase.com/docs/reference/dart/upgrade-guide

We are proceeding on the understanding that we have the necessary setup for apple login.

<img width="649" alt="スクリーンショット 2024-02-18 10 10 08" src="https://github.com/supabase/gotrue/assets/67954894/eb4aa6d6-d7cf-4e3a-b947-445cec248016">


<details><summary>Flutter Doctor</summary><div>

```terminal
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.0)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by hixcoder** [comment]
> Hello, I have been implementing `sign in with apple` since 2024/02/18. I have implemented sign in with apple since 2024/02/18, but I got the error `Unacceptable audience in id_token`.
> 
> I tried to turn off "sign in with Apple" and turn it on again as mentioned in the comments, but the error remained the same.
> 
> In my case, the address of the device to log in is an address that I have never registered, so I think the situation is different from what is outlined in the issue, but I am facing the same error.
> 
> As for the login implementation, it is exactly the same as the new Apple login implementation at
> 
> https://supabase.com/docs/reference/dart/upgrade-guide
> 
> We are proceeding on the understanding that we have the necessary setup for apple login.
> <img alt="スクリーンショット 2024-02-18 10 10 08" width="649" src="https://private-user-images.githubusercontent.com/67954894/305678409-eb4aa6d6-d7cf-4e3a-b947-445cec248016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDY0MDQsIm5iZiI6MTcyNTY0NjEwNCwicGF0aCI6Ii82Nzk1NDg5NC8zMDU2Nzg0MDktZWI0YWE2ZDYtZDdjZi00ZTNhLWI5NDctNDQ1Y2VjMjQ4MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE4MDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYmExMDhkODQxNTg3ZjE0OTM0YzU0ZTM0ZmYzMmM1ODVmNTU2ZDAwNmZjOWRkMjAzMjc3NTU0YmFlZGM3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nds_zyTyikfXQjoKyL1NE8hmd13sDeLUhNDTEYvBvX4">
> Flutter Doctor
> 
> ```
> [✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale ja-JP)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.2)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.3)
> [✓] VS Code (version 1.86.0)
> [✓] Connected device (4 available)
> [✓] Network resources
> ```　
> ```

hello bro, I face the same issue , did you find a solution?
